### ISSUE TITLE
Doesn't build with monad-logger 0.3.26

### ISSUE THREAD

**Issue by felixonmars** [fpco/unliftio#8]
```
[ 7 of 13] Compiling UnliftIO.Instances ( src/UnliftIO/Instances.hs, dist/build/UnliftIO/Instances.dyn_o )

src/UnliftIO/Instances.hs:11:10: error:
    Duplicate instance declarations:
      instance MonadUnliftIO m => MonadUnliftIO (LoggingT m)
        -- Defined at src/UnliftIO/Instances.hs:11:10
      instance MonadUnliftIO m => MonadUnliftIO (LoggingT m)
        -- Defined in ‘Control.Monad.Logger’
   |
11 | instance MonadUnliftIO m => MonadUnliftIO (LoggingT m) where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/UnliftIO/Instances.hs:17:10: error:
    Duplicate instance declarations:
      instance MonadUnliftIO m => MonadUnliftIO (NoLoggingT m)
        -- Defined at src/UnliftIO/Instances.hs:17:10
      instance MonadUnliftIO m => MonadUnliftIO (NoLoggingT m)
        -- Defined in ‘Control.Monad.Logger’
   |
17 | instance MonadUnliftIO m => MonadUnliftIO (NoLoggingT m) where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by snoyberg** [comment]
New release is coming soon that removes the orphans.

**Comment by snoyberg** [comment]
unliftio-0.2.0.0 is now on Hackage.
